name: at_cram_cli
description: Dart command line tool to generate atKeys file from a CRAM key
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  at_onboarding_cli: ^1.0.0
  args: ^2.3.1
